# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuadroControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_actividades", models.PositiveIntegerField(default=0)),
                ("completadas", models.PositiveIntegerField(default=0)),
                (
                    "avance_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cuadro de Control",
                "verbose_name_plural": "Cuadros de Control",
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("supervisor", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("en_ejecucion", "En Ejecución"),
                            ("finalizado", "Finalizado"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="planificado",
                        max_length=30,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
