# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_responsables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cuadrocontrol",
            name="proyecto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control",
                to="proyectos.proyecto",
            ),
        ),
    ]
