# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(blank=True, max_length=20, null=True)),
                ("descripcion", models.TextField()),
                ("fecha_programada", models.DateField(blank=True, null=True)),
                ("fecha_real", models.DateField(blank=True, null=True)),
                (
                    "avance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_ejecucion", "En Ejecución"),
                            ("completada", "Completada"),
                            ("atrasada", "Atrasada"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["proyecto", "fecha_programada"],
            },
        ),
    ]
