# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0001_initial"),
        ("actividades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="proyectos.proyecto",
            ),
        ),
    ]
