# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoConformidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("causa", models.TextField(blank=True, null=True)),
                ("accion_correctiva", models.TextField(blank=True, null=True)),
                ("fecha_detectada", models.DateField()),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_proceso", "En Proceso"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "No Conformidad",
                "verbose_name_plural": "No Conformidades",
                "ordering": ["-fecha_detectada"],
            },
        ),
    ]
