# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("noc", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noconformidad",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="noc_responsables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
