# Generated by Django 4.2.26 on 2025-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rut", models.CharField(blank=True, max_length=20, null=True)),
                ("contacto", models.CharField(blank=True, max_length=200, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
    ]
